CREATE TABLE `audio_files` (
	`id` text PRIMARY KEY NOT NULL,
	`media_id` text NOT NULL,
	`index` integer NOT NULL,
	`ino` text NOT NULL,
	`filename` text NOT NULL,
	`ext` text,
	`path` text NOT NULL,
	`rel_path` text,
	`size` integer,
	`mtime_ms` real,
	`ctime_ms` real,
	`birthtime_ms` real,
	`added_at` integer,
	`updated_at` integer,
	`track_num_from_meta` integer,
	`disc_num_from_meta` integer,
	`track_num_from_filename` integer,
	`disc_num_from_filename` integer,
	`manually_verified` integer,
	`exclude` integer,
	`error` text,
	`format` text,
	`duration` real,
	`bit_rate` integer,
	`language` text,
	`codec` text,
	`time_base` text,
	`channels` integer,
	`channel_layout` text,
	`embedded_cover_art` text,
	`mime_type` text,
	`tag_album` text,
	`tag_artist` text,
	`tag_genre` text,
	`tag_title` text,
	`tag_series` text,
	`tag_series_part` text,
	`tag_subtitle` text,
	`tag_album_artist` text,
	`tag_date` text,
	`tag_composer` text,
	`tag_publisher` text,
	`tag_comment` text,
	`tag_language` text,
	`tag_asin` text,
	`is_downloaded` integer DEFAULT false,
	`download_path` text,
	`downloaded_at` integer,
	FOREIGN KEY (`media_id`) REFERENCES `media_metadata`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `chapters` (
	`id` text PRIMARY KEY NOT NULL,
	`media_id` text NOT NULL,
	`chapter_id` integer NOT NULL,
	`start` real NOT NULL,
	`end` real NOT NULL,
	`title` text NOT NULL,
	FOREIGN KEY (`media_id`) REFERENCES `media_metadata`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `library_files` (
	`id` text PRIMARY KEY NOT NULL,
	`library_item_id` text NOT NULL,
	`ino` text NOT NULL,
	`filename` text NOT NULL,
	`ext` text,
	`path` text NOT NULL,
	`rel_path` text,
	`size` integer,
	`mtime_ms` real,
	`ctime_ms` real,
	`birthtime_ms` real,
	`is_supplementary` integer,
	`added_at` integer,
	`updated_at` integer,
	`file_type` text,
	`is_downloaded` integer DEFAULT false,
	`download_path` text,
	`downloaded_at` integer,
	FOREIGN KEY (`library_item_id`) REFERENCES `library_items`(`id`) ON UPDATE no action ON DELETE cascade
);
